version: "3.9"

services:
  postgres:
    image: postgres:18          # Latest PostgreSQL 18.x image
    container_name: green_postgres
    environment:
      POSTGRES_USER: green
      POSTGRES_PASSWORD: green
      POSTGRES_DB: trips
    ports:
      - "5432:5432"
    volumes:
      # Use a named volume, so Postgres will manage the correct path internally
      - pgdata:/var/lib/postgresql

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: green
      POSTGRES_PASSWORD: green
      POSTGRES_DB: trips
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: python src/ingest.py

volumes:
  pgdata:
