version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: green_taxi_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: green_taxi
      POSTGRES_PASSWORD: green_taxi
      POSTGRES_DB: green_taxi

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U green_taxi"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: green_taxi_pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"

    ports:
      - "8080:80"

    depends_on:
      postgres:
        condition: service_healthy

  module1-greentaxi:
    image: module1-greentaxi:latest
    container_name: module1-greentaxi
    restart: "no"

    environment:
      DATABASE_URL: postgresql+psycopg2://green_taxi:green_taxi@postgres:5432/green_taxi
      PYTHONUNBUFFERED: "1"

    depends_on:
      postgres:
        condition: service_healthy

    command: ["python", "-m", "pipeline.main"]

networks:
  default:
    name: green_taxi_network

volumes:
  postgres_data:
